// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PromVesClientPlatform;

#nullable disable

namespace PromVesClientPlatform.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260908045105_UpdateColumnWeighing")]
    partial class UpdateColumnWeighing
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PromVesClientPlatform.Model.Receipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Receipts");
                });

            modelBuilder.Entity("PromVesClientPlatform.Model.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PromVesClientPlatform.Model.Weighing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("AnimalNumber")
                        .HasColumnType("numeric");

                    b.Property<string>("Brigade")
                        .HasColumnType("text");

                    b.Property<decimal>("CurrentWeighing")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("DatePreviousWeighing")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Department")
                        .HasColumnType("text");

                    b.Property<string>("GroupAnimals")
                        .HasColumnType("text");

                    b.Property<decimal?>("PreviousWeigh")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ReceiptId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResponsibleEmployee")
                        .HasColumnType("text");

                    b.Property<DateTime>("WeighingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("WeightGain")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ReceiptId");

                    b.ToTable("Weighings");
                });

            modelBuilder.Entity("PromVesClientPlatform.Model.Weighing", b =>
                {
                    b.HasOne("PromVesClientPlatform.Model.Receipt", "Receipt")
                        .WithMany("Weighings")
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("PromVesClientPlatform.Model.Receipt", b =>
                {
                    b.Navigation("Weighings");
                });
#pragma warning restore 612, 618
        }
    }
}
